In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import skew, kurtosis

In [43]:
movie_ratings = np.array([
    [5, 1, 4],
    [4, 4, 2],
    [4, 3, 5],
    [1, 1, 5],
    [3, 2, 1]
])

average_rating = np.mean(movie_ratings, axis=1, dtype=int)
viewer_preferance = np.max(movie_ratings, axis=1)


print(f"Average Rating: {average_rating}")
print(f"Viewer preferance: {viewer_preferance}")

Average Rating: [3 3 4 2 2]
Viewer preferance: [5 4 5 5 3]


In [44]:
matrix_B = np.array([[2, 3], [4, 5]])
matrix_C = np.array([[1, 1], [1, 1]])

sum_matrix = np.add(matrix_B, matrix_C)
diff_matrix = np.subtract(matrix_B, matrix_C)

print(f"Sum of Matrices: {sum_matrix}")
print(f"Diff of Matrices: {diff_matrix}")

Sum of Matrices: [[3 4]
 [5 6]]
Diff of Matrices: [[1 2]
 [3 4]]


In [45]:
matrix_1 = np.random.rand(3, 3)
matrix_2 = np.random.rand(3, 3)

matrix_sum = np.add(matrix_1, matrix_2)
matrix_sub = np.subtract(matrix_1, matrix_2)
print(f"Sum: {matrix_sum}")
print(f"Sum: {matrix_sub}")

Sum: [[1.65488503 1.40555673 1.5245952 ]
 [1.18249042 1.08812956 1.09892808]
 [1.38559666 1.45491968 0.94653625]]
Sum: [[ 0.33927643 -0.23481339 -0.40545036]
 [ 0.13578398 -0.34056165 -0.23950467]
 [-0.46425423  0.37947108 -0.86094855]]


In [46]:
# Temperature data matrix (4 cities, 7 days)
temperature_data = np.array([
    [27, 20, 15, 18, 26, 18, 22],
    [24, 18, 20, 17, 19, 22, 21],
    [23, 23, 27, 25, 16, 21, 22],
    [22, 29, 23, 16, 20, 24, 28]
])

average_temp = np.mean(temperature_data, axis=1, dtype=int)
max_temp = np.max(temperature_data, axis=1)
min_temp = np.min(temperature_data, axis=1)

day_one_avg = np.mean(temperature_data[:,0], dtype=int)
day_seven_avg = np.mean(temperature_data[:,6], dtype=int)

difference = day_one_avg, day_seven_avg

print(f"Average Temp Of each city: {average_temp}")
print(f"Max Temp Of each city: {max_temp}")
print(f"Min Temp Of each city: {min_temp}")
print(difference)


Average Temp Of each city: [20 20 22 23]
Max Temp Of each city: [27 24 27 29]
Min Temp Of each city: [15 17 16 16]
(np.int64(24), np.int64(23))


In [48]:
data = np.arange(20)
sample = np.random.choice(data, size=10, replace=False)

sample_mean = np.mean(sample)
sample_median = np.median(sample)
sample_varience = np.var(sample)
sample_skewness = skew(sample)
sample_kurtosis = kurtosis(sample)

print(sample)
print(sample_mean)
print(sample_median)
print(sample_varience)
print(sample_skewness)
print(sample_kurtosis)


[ 1  6 15  5  3 13  4 14  8  7]
7.6
6.5
21.240000000000002
0.37953377438477487
-1.206251928458191


In [49]:
dates =np.arange('2020-01', '2020-02', dtype='datetime64[D]')
print(dates)

['2020-01-01' '2020-01-02' '2020-01-03' '2020-01-04' '2020-01-05'
 '2020-01-06' '2020-01-07' '2020-01-08' '2020-01-09' '2020-01-10'
 '2020-01-11' '2020-01-12' '2020-01-13' '2020-01-14' '2020-01-15'
 '2020-01-16' '2020-01-17' '2020-01-18' '2020-01-19' '2020-01-20'
 '2020-01-21' '2020-01-22' '2020-01-23' '2020-01-24' '2020-01-25'
 '2020-01-26' '2020-01-27' '2020-01-28' '2020-01-29' '2020-01-30'
 '2020-01-31']


In [60]:
dates = pd.date_range(start='2022-01', end='2022-02', freq='D')

temp_data = np.random.uniform(low=10, high=35, size=len(dates))

humidity = np.random.uniform(low=30, high=90, size=len(dates))

data = {
    'Date': dates, 
    'Tempuratue': temp_data, 
    'Humidity %': humidity
}

df = pd.DataFrame(data)
df.head()

Date  Tempuratue  Humidity %
0 2022-01-01   33.437455   77.640990
1 2022-01-02   10.766032   61.036763
2 2022-01-03   25.814954   46.575178
3 2022-01-04   24.096465   87.146705
4 2022-01-05   22.630749   81.008766

In [62]:
temp_mean = np.mean(df['Tempuratue'])
temp_median = np.median(df['Tempuratue'])
temp_std = np.std(df['Tempuratue'])

humidity_mean = np.mean(df['Humidity %'])
humidity_median = np.median(df['Humidity %'])
humidity_std = np.std(df['Humidity %'])

print(temp_mean)
print(temp_median)
print(temp_std)

print(humidity_mean)
print(humidity_median)
print(humidity_std)

25.684200647987435
26.81000683326077
7.134081389890149
62.172166140897005
61.70821741768052
17.47658173044199


Use a rolling window of 7 days to calculate the moving average for both temperature and humidity.
[bonus] Plot the original data and the 7-day moving average on the same graph for comparison.

In [64]:
df['Temp_MA7'] = df['Tempuratue'].rolling(window=7).mean()
df['Humidity_MA7'] = df['Humidity %'].rolling(window=7).mean()